sectors = [
    {
        name:'cube_suelo',
        z0:0,
        z1:-30,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [-1000, -1000, 'brick.png'],
            [1000, -1000, 'brick.png'],
            [1000, 1000, 'brick.png'],
            [-1000, 1000, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:200,
        z1:0,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 0, 'brick.png'],
            [200, 0, 'brick.png'],
            [200, 200, 'brick.png'],
            [0, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_puente',
        z0:100,
        z1:80,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 200, 'brick.png'],
            [200, 200, 'brick.png'],
            [200, 600, 'brick.png'],
            [0, 600, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_puente_top',
        z0:200,
        z1:180,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 200, 'brick.png'],
            [200, 200, 'brick.png'],
            [200, 600, 'brick.png'],
            [0, 600, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },

    {
        name:'cube_techo',
        z0:220,
        z1:200,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [-1000, -1000, 'brick.png'],
            [1000, -1000, 'brick.png'],
            [1000, 1000, 'brick.png'],
            [-1000, 1000, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'piscina',
        z0:30,
        z1:20,
        ceil_color:'wood.jpg',
        ceil_scale:1,
        floor_color:'wood.jpg',
        floor_scale:1,
        points:[
            [300, 200, 'wood.jpg'],
            [500, 200, 'wood.jpg'],
            [500, 600, 'wood.jpg'],
            [300, 600, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'sprite',
        z0:50,
        z1:30,
        ceil_color:'wood.jpg',
        ceil_scale:1,
        floor_color:'wood.jpg',
        floor_scale:1,
        points:[
            [350, 450, 'wood.jpg'],
            [450, 450, 'wood.jpg'],
            [450, 550, 'wood.jpg'],
            [350, 550, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
]

sprites = [
    /*{
        posx: 350,
        posy: 350,
        posz: -10,
        texture: 'mario.png',
        texture_scale_h: 0.4,
        texture_scale_w: 5,
        height: 40,
        width: 50,
    },*/
]