sectors = [
    {
        name:'cube_suelo',
        z0:0, z1:-30,
        ceil_color:'ceiling.png', ceil_scale:1, ceil_light:1,
        floor_color:'floor.jpg',floor_scale:1, floor_light:1,
        points:[
            [-1000, -1000, 'brick.png', 1],
            [1000, -1000, 'brick.png', 1],
            [1000, 1000, 'brick.png', 1],
            [-1000, 1000, 'brick.png', 1],
        ],
        texture_h: 200,texture_w: 2,
        texture_x0: 0,texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:200,  z1:0,
        ceil_color:'floor.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'ceiling.png', floor_scale:1, floor_light:1,
        points:[
            [0, 0, 'brick.png', 0],
            [200, 0, 'brick.png', 0],
            [200, 200, 'brick.png', 0],
            [0, 200, 'brick.png', 0],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:200, z1:0,
        ceil_color:'floor.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'ceiling.png', floor_scale:1, floor_light:1,
        points:[
            [-50, 50, 'transparent.png', 1],
            [0, 50, 'transparent.png', 1],
            [0, 100, 'transparent.png', 1],
            [-50, 100, 'transparent.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'cube_puente',
        z0:100,
        z1:80,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        ceil_light:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        floor_light:1,
        points:[
            [0, 200, 'brick.png', 1],
            [200, 200, 'brick.png', 1],
            [200, 600, 'brick.png', 1],
            [0, 600, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_puente_top',
        z0:200,
        z1:180,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
        floor_color:'ceiling.png',
        floor_scale:1,
floor_light:1,
        points:[
            [0, 200, 'brick.png', 1],
            [200, 200, 'brick.png', 1],
            [200, 600, 'brick.png', 1],
            [0, 600, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },

    {
        name:'cube_techo',
        z0:220, z1:200,
        ceil_color:'ceiling.png', ceil_scale:1, ceil_light:1,
        floor_color:'floor2.jpg', floor_scale:1, floor_light:1,
        points:[
            [-500, -1000, 'brick.png', 1],
            [1000, -1000, 'brick.png', 1],
            [1000, 1000, 'brick.png', 1],
            [-500, 1000, 'brick.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'piscina',
        z0:30,
        z1:20,
        ceil_color:'wood.jpg',
        ceil_scale:1,
ceil_light:1,
        floor_color:'wood.jpg',
        floor_scale:1,
floor_light:1,
        points:[
            [300, 200, 'wood.jpg', 1],
            [500, 200, 'wood.jpg', 1],
            [500, 600, 'wood.jpg', 1],
            [300, 600, 'wood.jpg', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'sprite',
        z0:50,
        z1:30,
        ceil_color:'wood.jpg',
        ceil_scale:1,
ceil_light:1,
        floor_color:'wood.jpg',
        floor_scale:1,
floor_light:1,
        points:[
            [350, 450, 'wood.jpg', 1],
            [450, 450, 'wood.jpg', 1],
            [450, 550, 'wood.jpg', 1],
            [350, 550, 'wood.jpg', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'glass1',
        z0:120, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1,
ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1,
floor_light:1,
        points:[
            [200, -100, 'transparent.png', 1],
            [300, -200, 'transparent.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'glass2',
        z0:120, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1,
ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1,
floor_light:1,
        points:[
            [300, -200, 'transparent.png', 1],
            [400, -150, 'transparent.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 6, texture_y0: 0,
    },
    {
        name:'glass_wood',
        z0:100, z1:100,
        ceil_color:'wood.jpg', ceil_scale:1,
ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1,
floor_light:1,
        points:[
            [200, -100, 'transparent.png', 1],
            [300, -200, 'transparent.png', 1],
            [400, -150, 'transparent.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'tree',
        type:'sprite',
        z0:60, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        points:[
            [-10, 0, 'duke.png', 1],
            [10, 0, 'duke.png', 1],
        ],
        texture_h: 325, texture_w: 8,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'tree2',
        type:'sprite',
        z0:140, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        posx:0,posy:0,posz:0,height:130,
        points:[
            [300, 0, 'tree.png', 1],
            [400, 0, 'tree.png', 1],
        ],
        texture_h: 360, texture_w: 4,
        texture_x0: 6, texture_y0: 0,
    },
    {
        name:'escalera_0',
        z0:20, z1:0,
        ceil_color:'floor.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, 200, 'brick.png', 1],
            [-600, 200, 'brick.png', 1],
            [-600, 400, 'brick.png', 1],
            [-800, 400, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_1',
        z0:40,
        z1:20,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, 100, 'brick.png', 1],
            [-600, 100, 'brick.png', 1],
            [-600, 300, 'brick.png', 1],
            [-800, 300, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_2',
        z0:60,
        z1:40,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, 0, 'brick.png', 1],
            [-600, 0, 'brick.png', 1],
            [-600, 200, 'brick.png', 1],
            [-800, 200, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_3',
        z0:80,
        z1:60,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -100, 'brick.png', 1],
            [-600, -100, 'brick.png', 1],
            [-600, 100, 'brick.png', 1],
            [-800, 100, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_4',
        z0:100,
        z1:80,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -200, 'brick.png', 1],
            [-600, -200, 'brick.png', 1],
            [-600, 0, 'brick.png', 1],
            [-800, 0, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_5',
        z0:120,
        z1:100,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -300, 'brick.png', 1],
            [-600, -300, 'brick.png', 1],
            [-600, -100, 'brick.png', 1],
            [-800, -100, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_6',
        z0:140,
        z1:120,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -400, 'brick.png', 1],
            [-400, -400, 'brick.png', 1],
            [-400, -200, 'brick.png', 1],
            [-800, -200, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_7',
        z0:160,
        z1:140,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -500, 'brick.png', 1],
            [-400, -500, 'brick.png', 1],
            [-400, -300, 'brick.png', 1],
            [-800, -300, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_8',
        z0:180,
        z1:160,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -600, 'brick.png', 1],
            [-400, -600, 'brick.png', 1],
            [-400, -400, 'brick.png', 1],
            [-800, -400, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_9',
        z0:200,
        z1:180,
        ceil_color:'floor.jpg',
        ceil_scale:1,
ceil_light:1,
floor_color:'tiles.jpg', floor_scale:6, floor_light:1,
        points:[
            [-800, -700, 'brick.png', 1],
            [-400, -700, 'brick.png', 1],
            [-400, -500, 'brick.png', 1],
            [-800, -500, 'brick.png', 1],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
//habitacion
    {
        name:'habitacion',
        z0:120, z1:0,
        ceil_color:'brick2.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'brick2.jpg', floor_scale:1, floor_light:1,
        points:[
            [100, -900, 'brick2.jpg', 1],
            [500, -900, 'brick2.jpg', 1],
            [500, -500, 'brick2.jpg', 1],
            [300, -500, 'wall.jpg', 1],
            [300, -510, 'wall.jpg', 1],
            [490, -510, 'wall.jpg', 1],
            [490, -890, 'wall.jpg', 1],
            [110, -890, 'wall.jpg', 1],
            [110, -510, 'wall.jpg', 1],
            [200, -510, 'wall.jpg', 1],
            [200, -500, 'brick2.jpg', 1],
            [100, -500, 'brick2.jpg', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'habitacion_techo',
        z0:120, z1:100,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'brick2.jpg', floor_scale:1, floor_light:1,
        points:[
            [300, -500, 'brick2.jpg', 1],
            [300, -510, 'brick2.jpg', 1],
            [490, -510, 'brick2.jpg', 1],
            [490, -890, 'brick2.jpg', 1],
            [110, -890, 'brick2.jpg', 1],
            [110, -510, 'brick2.jpg', 1],
            [200, -510, 'brick2.jpg', 1],
            [200, -500, 'brick2.jpg', 1],
        ],
        texture_h: 34, texture_w: 2,
        texture_x0: 12, texture_y0: 0,
    },
    {
        name:'habitacion_suelo',
        z0:5, z1:0,
        ceil_color:'brick2.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'parquet.jpg', floor_scale:5, floor_light:1,
        points:[
            [300, -500, 'brick2.jpg', 1],
            [300, -510, 'brick2.jpg', 1],
            [490, -510, 'brick2.jpg', 1],
            [490, -890, 'brick2.jpg', 1],
            [110, -890, 'brick2.jpg', 1],
            [110, -510, 'brick2.jpg', 1],
            [200, -510, 'brick2.jpg', 1],
            [200, -500, 'brick2.jpg', 1],
        ],
        texture_h: 26, texture_w: 2,
        texture_x0: 12, texture_y0: 0,
    },
    {
        name:'habitacion_marco',
        z0:100, z1:80,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        points:[
            [300, -490, 'wood.jpg', 1],
            [300, -510, 'wood.jpg', 1],
            [200, -510, 'wood.jpg', 1],
            [200, -490, 'wood.jpg', 1],
        ],
        texture_h: 100, texture_w: 15,
        texture_x0: 12, texture_y0: 0,
    },
    {
        name:'habitacion_puerta_i',
        z0:80, z1:0,
        ceil_color:'door.png', ceil_scale:1, ceil_light:1,
        floor_color:'door.png', floor_scale:1, floor_light:1,
        points:[
            [200, -500, 'door.png', 1],
            [249, -500, 'door.png', 1],
            [250, -498, 'door.png', 1],
            [200, -498, 'door.png', 1],
        ],
        texture_h: 1000, texture_w: 8.7,
        texture_x0: 12, texture_y0: 0,
        action : 'door',
        params : {x:200,y:-498,a:100},
        status : 'closed'
    },
    {
        name:'habitacion_puerta_d',
        z0:80, z1:0,
        ceil_color:'door.png', ceil_scale:1, ceil_light:1,
        floor_color:'door.png', floor_scale:1, floor_light:1,
        points:[
            [251, -500, 'door.png', 1],
            [300, -500, 'door.png', 1],
            [300, -498, 'door.png', 1],
            [250, -498, 'door.png', 1],
        ],
        texture_h: 1000, texture_w: 8.7,
        texture_x0: 12, texture_y0: 0,
        action : 'door',
        params : {x:300,y:-498,a:-100},
        status : 'closed'
    },
    {
        name:'elevator',
        z0:20,
        z1:0,
        ceil_color:'floor.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'ceiling.png', floor_scale:1, floor_light:1,
        points:[
            [-800, 600, 'brick.png', 1],
            [-600, 600, 'brick.png', 1],
            [-600, 800, 'brick.png', 1],
            [-800, 800, 'brick.png', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
        animate: 'animateElevator',
        status:'up'
    },
    {
        name:'elevator_i',
        z0:160, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        points:[
            [-850, 550, 'wood.jpg', 1],
            [-800, 550, 'wood.jpg', 1],
            [-800, 600, 'wood.jpg', 1],
            [-850, 600, 'wood.jpg', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'elevator_c',
        z0:220, z1:160,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        points:[
            [-850, 550, 'wood.jpg', 1],
            [-800, 550, 'wood.jpg', 1],
            [-800, 900, 'wood.jpg', 1],
            [-850, 900, 'wood.jpg', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'elevator_d',
        z0:160, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
        floor_color:'wood.jpg', floor_scale:1, floor_light:1,
        points:[
            [-850, 850, 'wood.jpg', 1],
            [-800, 850, 'wood.jpg', 1],
            [-800, 900, 'wood.jpg', 1],
            [-850, 900, 'wood.jpg', 1],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
]

sectors = []

for(let i=0 ; i<10 ; i++){
    for(let j=0 ; j<10 ; j++){
        for(let k=0 ; k<10 ; k++){
            let facti = i*200
            let factj = j*200
            let factk = k*200
            sector = {
                name:'sector',
                z0:100+facti, z1:0+facti,
                ceil_color:'wood.jpg', ceil_scale:1, ceil_light:1,
                floor_color:'wood.jpg', floor_scale:1, floor_light:1,
                points:[
                    [0+factj, 0+factk, 'wood.jpg', 1],
                    [0+factj, 100+factk, 'wood.jpg', 1],
                    [100+factj, 100+factk, 'wood.jpg', 1],
                    [100+factj, 0+factk, 'wood.jpg', 1],
                ],
                texture_h: 200, texture_w: 2,
                texture_x0: 0, texture_y0: 0,
            }
            sectors.push(sector)
        }
    }
}