console.log('load level 1')

sectors = [
    {
        name:'cube',
        z0:30,
        z1:-30,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 0, 'brick.png'],
            [300, 0, 'brick.png'],
            [300, 300, 'brick.png'],
            [0, 300, 'brick.png'],
            [0, 200, 'brick.png'],
            [100, 200, 'brick.png'],
            [100, 100, 'brick.png'],
            [0, 100, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_top',
        z0:150,
        z1:90,
        ceil_color:'brick.png',
        ceil_scale:1,
        floor_color:'brick.png',
        floor_scale:1,
        points:[
            [0, 100, 'floor.jpg'],
            [300, 100, 'brick.png'],
            [300, 200, 'floor.jpg'],
            [0, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_top_middle',
        z0:90,
        z1:30,
        ceil_color:'brick.png',
        ceil_scale:1,
        floor_color:'brick.png',
        floor_scale:1,
        points:[
            [100, 100, 'floor.jpg'],
            [300, 100, 'brick.png'],
            [300, 200, 'floor.jpg'],
            [100, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_sub_middle',
        z0:-30,
        z1:-90,
        ceil_color:'brick.png',
        ceil_scale:1,
        floor_color:'brick.png',
        floor_scale:1,
        points:[
            [100, 100, 'floor.jpg'],
            [300, 100, 'brick.png'],
            [300, 200, 'floor.jpg'],
            [100, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_sub',
        z0:-90,
        z1:-150,
        ceil_color:'brick.png',
        ceil_scale:1,
        floor_color:'brick.png',
        floor_scale:1,
        points:[
            [0, 100, 'floor.jpg'],
            [300, 100, 'brick.png'],
            [300, 200, 'floor.jpg'],
            [0, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_arriba_tapa',
        z0:30,
        z1:10,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [0, 100, 'wood.jpg'],
            [100, 100, 'wood.jpg'],
            [100, 200, 'wood.jpg'],
            [0, 200, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_abajo_tapa',
        z0:-10,
        z1:-30,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [0, 100, 'wood.jpg'],
            [100, 100, 'wood.jpg'],
            [100, 200, 'wood.jpg'],
            [0, 200, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
]

sprites = [

]