sectors = [
    {
        name:'cube_suelo',
        z0:0,
        z1:-30,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [-1000, -1000, 'brick.png'],
            [1000, -1000, 'brick.png'],
            [1000, 1000, 'brick.png'],
            [-1000, 1000, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:200,
        z1:0,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 0, 'brick.png'],
            [200, 0, 'brick.png'],
            [200, 200, 'brick.png'],
            [0, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:200,
        z1:0,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-50, 50, 'transparent.png'],
            [0, 50, 'transparent.png'],
            [0, 100, 'transparent.png'],
            [-50, 100, 'transparent.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_puente',
        z0:100,
        z1:80,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 200, 'brick.png'],
            [200, 200, 'brick.png'],
            [200, 600, 'brick.png'],
            [0, 600, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_puente_top',
        z0:200,
        z1:180,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [0, 200, 'brick.png'],
            [200, 200, 'brick.png'],
            [200, 600, 'brick.png'],
            [0, 600, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },

    {
        name:'cube_techo',
        z0:220,
        z1:200,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:'floor.jpg',
        floor_scale:1,
        points:[
            [-500, -1000, 'brick.png'],
            [1000, -1000, 'brick.png'],
            [1000, 1000, 'brick.png'],
            [-500, 1000, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'piscina',
        z0:30,
        z1:20,
        ceil_color:'wood.jpg',
        ceil_scale:1,
        floor_color:'wood.jpg',
        floor_scale:1,
        points:[
            [300, 200, 'wood.jpg'],
            [500, 200, 'wood.jpg'],
            [500, 600, 'wood.jpg'],
            [300, 600, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'sprite',
        z0:50,
        z1:30,
        ceil_color:'wood.jpg',
        ceil_scale:1,
        floor_color:'wood.jpg',
        floor_scale:1,
        points:[
            [350, 450, 'wood.jpg'],
            [450, 450, 'wood.jpg'],
            [450, 550, 'wood.jpg'],
            [350, 550, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'glass1',
        z0:120, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1,
        floor_color:'wood.jpg', floor_scale:1,
        points:[
            [200, -100, 'transparent.png'],
            [300, -200, 'transparent.png'],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'glass2',
        z0:120, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1,
        floor_color:'wood.jpg', floor_scale:1,
        points:[
            [300, -200, 'transparent.png'],
            [400, -150, 'transparent.png'],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 6, texture_y0: 0,
    },
    {
        name:'glass_wood',
        z0:100, z1:100,
        ceil_color:'wood.jpg', ceil_scale:1,
        floor_color:'wood.jpg', floor_scale:1,
        points:[
            [200, -100, 'transparent.png'],
            [300, -200, 'transparent.png'],
            [400, -150, 'transparent.png'],
        ],
        texture_h: 200, texture_w: 2,
        texture_x0: 0, texture_y0: 0,
    },
    {
        name:'tree',
        type:'sprite',
        z0:140, z1:0,
        ceil_color:'wood.jpg', ceil_scale:1,
        floor_color:'wood.jpg', floor_scale:1,
        points:[
            [300, 0, 'tree.png'],
            [400, 0, 'tree.png'],
        ],
        texture_h: 360, texture_w: 4,
        texture_x0: 6, texture_y0: 0,
    },
    {
        name:'escalera_0',
        z0:20,
        z1:0,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, 200, 'brick.png'],
            [-600, 200, 'brick.png'],
            [-600, 400, 'brick.png'],
            [-800, 400, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_1',
        z0:40,
        z1:20,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, 100, 'brick.png'],
            [-600, 100, 'brick.png'],
            [-600, 300, 'brick.png'],
            [-800, 300, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_2',
        z0:60,
        z1:40,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, 0, 'brick.png'],
            [-600, 0, 'brick.png'],
            [-600, 200, 'brick.png'],
            [-800, 200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_3',
        z0:80,
        z1:60,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -100, 'brick.png'],
            [-600, -100, 'brick.png'],
            [-600, 100, 'brick.png'],
            [-800, 100, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_4',
        z0:100,
        z1:80,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -200, 'brick.png'],
            [-600, -200, 'brick.png'],
            [-600, 0, 'brick.png'],
            [-800, 0, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_5',
        z0:120,
        z1:100,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -300, 'brick.png'],
            [-600, -300, 'brick.png'],
            [-600, -100, 'brick.png'],
            [-800, -100, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_6',
        z0:140,
        z1:120,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -400, 'brick.png'],
            [-400, -400, 'brick.png'],
            [-400, -200, 'brick.png'],
            [-800, -200, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_7',
        z0:160,
        z1:140,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -500, 'brick.png'],
            [-400, -500, 'brick.png'],
            [-400, -300, 'brick.png'],
            [-800, -300, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_8',
        z0:180,
        z1:160,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -600, 'brick.png'],
            [-400, -600, 'brick.png'],
            [-400, -400, 'brick.png'],
            [-800, -400, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'escalera_9',
        z0:200,
        z1:180,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:'ceiling.png',
        floor_scale:1,
        points:[
            [-800, -700, 'brick.png'],
            [-400, -700, 'brick.png'],
            [-400, -500, 'brick.png'],
            [-800, -500, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
]

sprites = [
    /*{
        posx: 350,
        posy: 350,
        posz: -10,
        texture: 'mario.png',
        texture_scale_h: 0.4,
        texture_scale_w: 5,
        height: 40,
        width: 50,
    },*/
]