console.log('load level 1')

sectors = [
    {
        name:'cube',
        z0:50,
        z1:-50,
        ceil_color:'floor.jpg',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [0, 0, 'brick.png'],
            [500, 0, 'brick.png'],
            [500, 500, 'brick.png'],
            [0, 500, 'brick.png'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_centro',
        z0:80,
        z1:60,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [200, 200, 'wood.jpg'],
            [300, 200, 'wood.jpg'],
            [300, 300, 'wood.jpg'],
            [200, 300, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_centr2',
        z0:120,
        z1:85,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [150, 200, 'wood.jpg'],
            [250, 200, 'wood.jpg'],
            [250, 300, 'wood.jpg'],
            [150, 300, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_fuera',
        z0:20,
        z1:-20,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [501, 200, 'wood.jpg'],
            [600, 200, 'wood.jpg'],
            [600, 300, 'wood.jpg'],
            [501, 300, null],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_arriba',
        z0:80,
        z1:40,
        ceil_color:'wood.jpg',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [200, 0, 'wood.jpg'],
            [300, 0, 'wood.jpg'],
            [300, 100, 'wood.jpg'],
            [200, 100, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_abajo',
        z0:-40,
        z1:-80,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [150, 0, 'wood.jpg'],
            [250, 0, 'wood.jpg'],
            [250, 100, 'wood.jpg'],
            [150, 100, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_arriba_solo',
        z0:80,
        z1:40,
        ceil_color:'ceiling.png',
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [200, 400, 'wood.jpg'],
            [300, 400, 'wood.jpg'],
            [300, 500, 'wood.jpg'],
            [200, 500, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },
    {
        name:'cube_arriba_solo_sin_techo',
        z0:80,
        z1:40,
        ceil_color:null,
        ceil_scale:1,
        floor_color:null,
        floor_scale:1,
        points:[
            [410, 410, 'wood.jpg'],
            [510, 410, 'wood.jpg'],
            [510, 510, 'wood.jpg'],
            [410, 510, 'wood.jpg'],
        ],
        texture_h: 200,
        texture_w: 2,
        texture_x0: 0,
        texture_y0: 0,
    },

]

sprites = [

]